brew "git"
brew "rbenv"
brew "zsh"

tap "caskroom/fonts"
cask "appcleaner"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "gitkraken"
cask "google-chrome"
cask "iterm2"
cask "visual-studio-code"
